### ISSUE TITLE
 the version of mxnet 

### ISSUE THREAD

**Issue by yzgrfsy** [zaixizhang/FLDetector#2]
hello ,could you please tell me the version of mxnet ,and so on 
when i run the train_minst.py on cpu  ,  "mat_inv = nd.linalg.inverse(mat)",error ,i change it to np.linalg.inv ,error agagin.

**Comment by zaixizhang** [comment]
Hi, we use the 1.7.0 version of mxnet.
By the way, what error did you encounter?
