### ISSUE TITLE
On the input of function lbfgs().

### ISSUE THREAD

**Issue by meitianyu** [zaixizhang/FLDetector#4]
Hello author, first of all thank you for your generous sharing.
Reading your code, I came across some questions to answer, and the question is about the function lbfgs(hvp = lbfgs(args, weight_record, grad_record, weight - last_weight)).Are the input weight_record and grad_record of the function using the global model? From my understanding, shouldn't the client's local weights and update gradients be used for prediction?

**Comment by CCCiciKK** [comment]
in the paper, the author mentioned that the server make the predictions of hvp. Therefore, the gradients and weights are global.

**Comment by zaixizhang** [comment]
Thanks for your comment! Yes, the global gradients and weights are used as the inputs of lbfgs function.
