### ISSUE TITLE
Where is VAE detection model?

### ISSUE THREAD

**Issue by CCCiciKK** [zaixizhang/FLDetector#5]
Hello author, thank you for open source. After reading the code I have a question, where is the comparative experiment part of the VAE detector?

**Comment by CCCiciKK** [comment]
And I have another question. When I reproduce the first row of Table 3 in the paper, which is MNIST and Untargeted Model Poisoning Attack, the accuracy of w/o FLDetector is still 94.2% (in the paper the accuracy is 69.5%), is it a problem with the parameters set by my experiment?
Here are my setting parameters: byz_type=full_trim, lr=0.0002, aggregation = simple_mean.
Looking forward to your response~

**Comment by zaixizhang** [comment]
Hi, thanks for your interest in our work. We did not organize and upload the VAE baseline model. Actually, there is no official implementation and you can build your VAE detector following its original paper.
